name: Remove working label when issue closed

on:
  issues:
    types: [closed]

jobs:
  rm-working:
    runs-on: ubuntu-latest
    steps:
      - name: Remove working label
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'remove-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: 'working,pr-welcome'
